// Auto Code — Gravicode Studios (Kang Fadhil)

using System.Text;
using Microsoft.Extensions.AI;
using Spectre.Console;

namespace AutoCode.Cli.Ui;

/// <summary>The start-up header and the transcript exporter.</summary>
public static class Banner
{
    public static void Render(AutoCodeSession session, Theme theme)
    {
        var grid = new Grid()
            .AddColumn(new GridColumn().PadRight(2))
            .AddColumn();

        grid.AddRow(
            $"[{theme.Accent}]▲[/]",
            $"[{theme.ToolName}]Auto Code[/] [{theme.Muted}]v{Version}[/]");

        grid.AddRow("", $"[{theme.Muted}]Gravicode Studios · Kang Fadhil[/]");
        grid.AddRow("", "");
        grid.AddRow("", $"[{theme.Muted}]{Markup.Escape(Shorten(session.WorkspaceRoot))}[/]");
        grid.AddRow("", $"[{theme.Muted}]{Markup.Escape(session.Profile.Name)} · {Markup.Escape(session.Profile.Model)}[/]");

        if (session.Permissions.Mode != Core.Permissions.PermissionMode.Ask)
            grid.AddRow("", $"[{theme.Warning}]{session.Permissions.Mode} mode[/]");

        AnsiConsole.Write(new Panel(grid)
        {
            Border = BoxBorder.Rounded,
            BorderStyle = new Style(theme.AccentColor),
            Padding = new Padding(1, 0, 2, 0),
        });

        var hints = new List<string> { "/help for commands", "Ctrl+C to interrupt" };

        if (session.ContextFiles.Count > 0)
            hints.Insert(0, $"{session.ContextFiles.Count} context file{(session.ContextFiles.Count == 1 ? "" : "s")} loaded");

        AnsiConsole.MarkupLine($"[{theme.Muted}]{string.Join("  ·  ", hints)}[/]");
        AnsiConsole.WriteLine();
    }

    public static string Version =>
        typeof(Banner).Assembly.GetName().Version is { } v ? $"{v.Major}.{v.Minor}.{v.Build}" : "1.0.0";

    private static string Shorten(string path)
    {
        var home = Environment.GetFolderPath(Environment.SpecialFolder.UserProfile, Environment.SpecialFolderOption.DoNotVerify);

        return path.StartsWith(home, Core.Utilities.WorkspacePath.PathComparison)
            ? "~" + path[home.Length..].Replace('\\', '/')
            : path.Replace('\\', '/');
    }
}

/// <summary>Renders a session transcript as markdown for <c>/export</c>.</summary>
public static class Transcript
{
    public static string ToMarkdown(AutoCodeSession session)
    {
        var builder = new StringBuilder();

        builder.Append("# Auto Code session ").Append(session.Session.Id).Append("\n\n")
               .Append("- Workspace: `").Append(session.WorkspaceRoot).Append("`\n")
               .Append("- Provider: ").Append(session.Profile.Name).Append(" · ").Append(session.Profile.Model).Append('\n')
               .Append("- Started: ").Append(session.Session.CreatedAt.LocalDateTime.ToString("yyyy-MM-dd HH:mm")).Append('\n')
               .Append("- Tokens: ").Append(session.Cost.InputTokens).Append(" in / ").Append(session.Cost.OutputTokens).Append(" out\n\n")
               .Append("---\n\n");

        foreach (var summary in session.Session.CompactionSummaries)
            builder.Append("> **Compacted earlier context**\n>\n> ").Append(summary.ReplaceLineEndings("\n> ")).Append("\n\n");

        foreach (var message in session.Loop.Messages)
        {
            if (message.Role == ChatRole.User)
            {
                builder.Append("## User\n\n").Append(message.Text.Trim()).Append("\n\n");
                continue;
            }

            if (message.Role == ChatRole.Assistant)
            {
                var text = message.Text.Trim();
                if (text.Length > 0)
                    builder.Append("## Assistant\n\n").Append(text).Append("\n\n");

                foreach (var call in message.Contents.OfType<FunctionCallContent>())
                    builder.Append("- 🔧 `").Append(call.Name).Append("`\n");

                if (message.Contents.OfType<FunctionCallContent>().Any())
                    builder.Append('\n');
            }
        }

        builder.Append("\n---\n\n_Generated by Auto Code — Gravicode Studios (Kang Fadhil)._\n");

        return builder.ToString();
    }
}
