using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using System.Reflection;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.Json.Schema;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;
using DotCode.Abstractions;

namespace DotCode.Sdk;

/// <summary>One call of a custom tool; <c>Arguments</c> are the raw arguments sent by the model.</summary>
public sealed record ToolInvocation(string SessionId, string ToolCallId, string ToolName, JsonElement Arguments);

/// <summary>The result of a tool call. A <see cref="string"/> converts to a successful text result.</summary>
public sealed record ToolResult(string TextResultForLlm, bool IsError = false)
{
    /// <summary>Images returned to the model (vision-capable models).</summary>
    public IReadOnlyList<ImagePart> Images { get; init; } = [];

    public static ToolResult Success(string text) => new(text);
    public static ToolResult Failure(string text) => new(text, IsError: true);
    public static implicit operator ToolResult(string text) => new(text);

    internal List<ContentPart> ToContent() => [new TextPart(TextResultForLlm), .. Images];
}

/// <summary>A tool implemented by your application and offered to the model. Create it with
/// <see cref="DefineTool{TArgs}(string, string, Func{TArgs, ToolInvocation, CancellationToken, Task{ToolResult}}, JsonTypeInfo{TArgs})"/>:
/// the parameters are a C# type, so the JSON schema is generated and a misspelled argument is a compile error.</summary>
/// <example>
/// <code>
/// public sealed record WeatherArgs([property: Description("City name")] string City, string? Unit = null);
///
/// [JsonSerializable(typeof(WeatherArgs))]
/// [JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
/// partial class ToolJson : JsonSerializerContext;
///
/// var weather = DotCodeTool.DefineTool("get_weather", "Weather for a city",
///     args => $"{args.City}: sunny", ToolJson.Default.WeatherArgs);
/// </code>
/// </example>
public sealed class DotCodeTool
{
    public required string Name { get; init; }
    public required string Description { get; init; }
    /// <summary>JSON Schema of the arguments (generated by <c>DefineTool</c>).</summary>
    public JsonElement InputSchema { get; init; } = DotCodeJson.Parse("{\"type\":\"object\",\"properties\":{}}");
    /// <summary>Read-only tools may run in plan mode. Custom tools never prompt for permission.</summary>
    public bool ReadOnly { get; init; }
    /// <summary>Runs the tool; exceptions are reported to the model.</summary>
    public required Func<ToolInvocation, CancellationToken, Task<ToolResult>> Handler { get; init; }

    /// <summary>A copy marked read-only.</summary>
    public DotCodeTool AsReadOnly() => new() { Name = Name, Description = Description, InputSchema = InputSchema, ReadOnly = true, Handler = Handler };

    // ------------------------------------------------------------------ NativeAOT-safe (source-generated JSON)

    /// <summary>Defines a tool whose arguments are <typeparamref name="TArgs"/> (serialized with <paramref name="args"/>,
    /// e.g. from a <see cref="JsonSerializerContext"/>). <see cref="DescriptionAttribute"/> on properties becomes
    /// the parameter description; constructor parameters without defaults and <c>required</c> members are required.</summary>
    public static DotCodeTool DefineTool<TArgs>(string name, string description,
        Func<TArgs, ToolInvocation, CancellationToken, Task<ToolResult>> handler, JsonTypeInfo<TArgs> args) =>
        new()
        {
            Name = name,
            Description = description,
            InputSchema = ToolSchema.For(args),
            Handler = async (invocation, ct) => await handler(ToolSchema.Bind(args, invocation.Arguments), invocation, ct).ConfigureAwait(false),
        };

    /// <summary>Defines a tool with a synchronous handler (see the async overload).</summary>
    public static DotCodeTool DefineTool<TArgs>(string name, string description, Func<TArgs, ToolResult> handler, JsonTypeInfo<TArgs> args) =>
        DefineTool<TArgs>(name, description, (a, _, _) => Task.FromResult(handler(a)), args);

    /// <summary>Defines a tool without parameters.</summary>
    public static DotCodeTool DefineTool(string name, string description, Func<ToolInvocation, CancellationToken, Task<ToolResult>> handler) =>
        new() { Name = name, Description = description, Handler = handler };

    // ------------------------------------------------------------------ reflection-based (JIT apps)

    /// <summary>Defines a tool using reflection-based JSON (camelCase, enums as strings). Prefer the
    /// <see cref="JsonTypeInfo{T}"/> overloads in trimmed or NativeAOT applications.</summary>
    [RequiresUnreferencedCode("Uses reflection-based JSON serialization; pass a JsonTypeInfo<TArgs> for trimmed/AOT apps.")]
    [RequiresDynamicCode("Uses reflection-based JSON serialization; pass a JsonTypeInfo<TArgs> for trimmed/AOT apps.")]
    public static DotCodeTool DefineTool<TArgs>(string name, string description, Func<TArgs, ToolInvocation, CancellationToken, Task<ToolResult>> handler) =>
        DefineTool(name, description, handler, ToolSchema.ReflectionTypeInfo<TArgs>());

    /// <inheritdoc cref="DefineTool{TArgs}(string, string, Func{TArgs, ToolInvocation, CancellationToken, Task{ToolResult}})"/>
    [RequiresUnreferencedCode("Uses reflection-based JSON serialization; pass a JsonTypeInfo<TArgs> for trimmed/AOT apps.")]
    [RequiresDynamicCode("Uses reflection-based JSON serialization; pass a JsonTypeInfo<TArgs> for trimmed/AOT apps.")]
    public static DotCodeTool DefineTool<TArgs>(string name, string description, Func<TArgs, ToolResult> handler) =>
        DefineTool(name, description, handler, ToolSchema.ReflectionTypeInfo<TArgs>());

    // ------------------------------------------------------------------ legacy

    [Obsolete("Hand-written schemas are not type-checked; use DotCodeTool.DefineTool with an arguments type.")]
    public static DotCodeTool Create(string name, string description, string inputSchemaJson, Func<JsonElement, CancellationToken, Task<string>> handler, bool readOnly = false) =>
        new()
        {
            Name = name, Description = description, InputSchema = DotCodeJson.Parse(inputSchemaJson), ReadOnly = readOnly,
            Handler = async (inv, ct) => await handler(inv.Arguments, ct).ConfigureAwait(false),
        };

    [Obsolete("Hand-written schemas are not type-checked; use DotCodeTool.DefineTool with an arguments type.")]
    public static DotCodeTool Create(string name, string description, string inputSchemaJson, Func<JsonElement, string> handler, bool readOnly = false) =>
        new()
        {
            Name = name, Description = description, InputSchema = DotCodeJson.Parse(inputSchemaJson), ReadOnly = readOnly,
            Handler = (inv, _) => Task.FromResult<ToolResult>(handler(inv.Arguments)),
        };

    /// <summary>Runs the handler and converts failures to an error result for the model.</summary>
    internal async Task<ToolResult> InvokeAsync(ToolInvocation invocation, CancellationToken ct)
    {
        try { return await Handler(invocation, ct).ConfigureAwait(false); }
        catch (Exception ex) when (ex is not OperationCanceledException) { return ToolResult.Failure("Error: " + ex.Message); }
    }
}

/// <summary>Raised when the model's arguments do not match the tool's arguments type.</summary>
public sealed class ToolArgumentException(string message) : Exception(message);

internal static class ToolSchema
{
    public static JsonElement For(JsonTypeInfo typeInfo)
    {
        var node = typeInfo.GetJsonSchemaAsNode(new JsonSchemaExporterOptions
        {
            TreatNullObliviousAsNonNullable = true,
            TransformSchemaNode = (context, schema) =>
            {
                if (schema is not JsonObject obj) return schema;
                var description = Describe(context.PropertyInfo?.AttributeProvider) ?? Describe(context.PropertyInfo?.AssociatedParameter?.AttributeProvider);
                if (context.PropertyInfo is null && context.TypeInfo.Type.GetCustomAttribute<DescriptionAttribute>() is { } typeDescription) description ??= typeDescription.Description;
                if (description is not null) obj.Insert(0, "description", description);
                return obj;
            },
        });
        if (node is JsonObject root && typeInfo.Kind == JsonTypeInfoKind.Object)
        {
            var required = Required(typeInfo);
            root.Remove("required");
            if (required.Count > 0) root["required"] = new JsonArray([.. required.Select(r => (JsonNode?)JsonValue.Create(r))]);
            root["additionalProperties"] = false;
        }
        return DotCodeJson.Parse(node.ToJsonString());
    }

    private static string? Describe(ICustomAttributeProvider? provider) =>
        provider?.GetCustomAttributes(typeof(DescriptionAttribute), inherit: true).OfType<DescriptionAttribute>().FirstOrDefault()?.Description;

    private static List<string> Required(JsonTypeInfo typeInfo) =>
        [.. typeInfo.Properties.Where(p => p.IsRequired || p.AssociatedParameter is { HasDefaultValue: false, IsNullable: false }).Select(p => p.Name)];

    public static TArgs Bind<TArgs>(JsonTypeInfo<TArgs> typeInfo, JsonElement arguments)
    {
        var input = arguments.ValueKind is JsonValueKind.Undefined or JsonValueKind.Null ? DotCodeJson.EmptyObject : arguments;
        if (typeInfo.Kind == JsonTypeInfoKind.Object)
        {
            if (input.ValueKind != JsonValueKind.Object) throw new ToolArgumentException("arguments: expected an object");
            foreach (var name in Required(typeInfo))
                if (!input.TryGetProperty(name, out var v) || v.ValueKind == JsonValueKind.Null) throw new ToolArgumentException($"{name}: is required");
        }
        try { return input.Deserialize(typeInfo)!; }
        catch (JsonException ex) { throw new ToolArgumentException($"invalid arguments: {ex.Message}"); }
    }

    [RequiresUnreferencedCode("Reflection-based JSON")]
    [RequiresDynamicCode("Reflection-based JSON")]
    public static JsonTypeInfo<TArgs> ReflectionTypeInfo<TArgs>()
    {
        var options = new JsonSerializerOptions(JsonSerializerDefaults.Web) { TypeInfoResolver = new DefaultJsonTypeInfoResolver() };
        options.Converters.Add(new JsonStringEnumConverter());
        return (JsonTypeInfo<TArgs>)options.GetTypeInfo(typeof(TArgs));
    }
}
