using System.Text.Json;
using System.Text.Json.Serialization;

namespace Marbots.Abstractions;

/// <summary>Source-generated JSON metadata for every persisted or transported contract.</summary>
[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    UseStringEnumConverter = true,
    WriteIndented = false)]
[JsonSerializable(typeof(BotDefinition))]
[JsonSerializable(typeof(List<BotDefinition>))]
[JsonSerializable(typeof(BotTemplate))]
[JsonSerializable(typeof(List<BotTemplate>))]
[JsonSerializable(typeof(ChatThread))]
[JsonSerializable(typeof(List<ChatThread>))]
[JsonSerializable(typeof(ChatMessage))]
[JsonSerializable(typeof(List<ChatMessage>))]
[JsonSerializable(typeof(TaskRecord))]
[JsonSerializable(typeof(List<TaskRecord>))]
[JsonSerializable(typeof(ApprovalRequest))]
[JsonSerializable(typeof(List<ApprovalRequest>))]
[JsonSerializable(typeof(MemoryRecord))]
[JsonSerializable(typeof(List<MemoryRecord>))]
[JsonSerializable(typeof(SkillInfo))]
[JsonSerializable(typeof(List<SkillInfo>))]
[JsonSerializable(typeof(McpServerConfig))]
[JsonSerializable(typeof(List<McpServerConfig>))]
[JsonSerializable(typeof(ScheduleJob))]
[JsonSerializable(typeof(List<ScheduleJob>))]
[JsonSerializable(typeof(HostInfo))]
[JsonSerializable(typeof(HostFrame))]
[JsonSerializable(typeof(ThreadHost))]
[JsonSerializable(typeof(List<HostFilePayload>))]
[JsonSerializable(typeof(HostRecord))]
[JsonSerializable(typeof(List<HostRecord>))]
[JsonSerializable(typeof(HostEnrollment))]
[JsonSerializable(typeof(HostEnrollmentRequest))]
[JsonSerializable(typeof(HostEnrollmentResult))]
[JsonSerializable(typeof(HostCertificateRenewal))]
[JsonSerializable(typeof(HostCertificateResult))]
[JsonSerializable(typeof(ProvisionHostRequest))]
[JsonSerializable(typeof(ProvisionHostResult))]
[JsonSerializable(typeof(CreateEnrollmentRequest))]
[JsonSerializable(typeof(CreateEnrollmentResult))]
[JsonSerializable(typeof(SshBootstrapRequest))]
[JsonSerializable(typeof(SshBootstrapResult))]
[JsonSerializable(typeof(ContainerProfile))]
[JsonSerializable(typeof(List<HostFileEntry>))]
[JsonSerializable(typeof(List<HostInfo>))]
[JsonSerializable(typeof(AgentEvent))]
[JsonSerializable(typeof(List<AgentEvent>))]
[JsonSerializable(typeof(ModelProfile))]
[JsonSerializable(typeof(ProviderConfig))]
[JsonSerializable(typeof(WorkspaceSettings))]
[JsonSerializable(typeof(ChannelConfig))]
[JsonSerializable(typeof(List<ChannelConfig>))]
[JsonSerializable(typeof(ChannelConversation))]
[JsonSerializable(typeof(TriggerConfig))]
[JsonSerializable(typeof(List<TriggerConfig>))]
[JsonSerializable(typeof(SkillStats))]
[JsonSerializable(typeof(List<SkillStats>))]
[JsonSerializable(typeof(SkillEvaluation))]
[JsonSerializable(typeof(List<SkillEvaluation>))]
[JsonSerializable(typeof(List<TodoItem>))]
[JsonSerializable(typeof(TenantRecord))]
[JsonSerializable(typeof(List<TenantRecord>))]
[JsonSerializable(typeof(TenantApiKey))]
[JsonSerializable(typeof(List<TenantApiKey>))]
[JsonSerializable(typeof(TenantMember))]
[JsonSerializable(typeof(List<TenantMember>))]
[JsonSerializable(typeof(CreateTenantRequest))]
[JsonSerializable(typeof(CreateApiKeyRequest))]
[JsonSerializable(typeof(CreateApiKeyResult))]
[JsonSerializable(typeof(SetMemberRequest))]
[JsonSerializable(typeof(WhoAmI))]
[JsonSerializable(typeof(PushDevice))]
[JsonSerializable(typeof(List<PushDevice>))]
[JsonSerializable(typeof(RegisterPushDeviceRequest))]
[JsonSerializable(typeof(PushTestResult))]
[JsonSerializable(typeof(PushConfig))]
[JsonSerializable(typeof(TrustedSkillPublisher))]
[JsonSerializable(typeof(List<SkillPublisherInfo>))]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSerializable(typeof(List<string>))]
public sealed partial class MarbotsJsonContext : JsonSerializerContext
{
    private static MarbotsJsonContext? _indented;

    /// <summary>Indented variant for human-facing exports (.marbot manifests).</summary>
    public static MarbotsJsonContext Indented => _indented ??= new MarbotsJsonContext(new JsonSerializerOptions(Default.Options) { WriteIndented = true });
}
